# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: maven

on:
  push:
    branches: [ "maven-testes" ]
  pull_request:
    branches: [ "maven-testes" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -f "Source Code Inspection/pom.xml" clean package

    - name: Test Maven Project
      run: mvn -f "Source Code Inspection/pom.xml" test

    - name: Display Test Results
      run: |
        if [ -d "Source Code Inspection/target/surefire-reports" ]; then
          echo "Test Results:"
          cat "Source Code Inspection/target/surefire-reports"/*.txt
        else
          echo "No test reports found."
        fi

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      with:
        working-directory: "Source Code Inspection"

